### ISSUE TITLE
Mixer Pivotal Mooring for SBRs and Digesters Calculations Flag. 

### ISSUE THREAD

**Issue by chukon** [AquaAerobicSystemsInc/APD-Enhancements#1]
There is a simplistic excel sheet that we use for this now.  Opening the sheet, entering the values and pulling the group into the cost takes about 5 minutes per time.  With about half of digesters and 20% of SBRs in 15 designs per month using the calculation.

**Comment by phstanek** [comment]
Part 1 checked in as Changeset 444 and is ready for testing on APD Dev.  Do not merge.

Part 1 includes an update of the tmplfrmSBREquipmentTabs template form which now incorporates the angle calculation from the **commonwall calcs.xls** spreadsheet, including the ability to save the selected post length to the database.  Additionally, sub **ClonetblSBRUserInputs** from **Design Duplication.vb** was updated to include the new database field, **s101DewateringPostLength**.

After the updates from Part 1 have been tested successfully, Part 2 development will commence (consisting of adding the same modifications to Digesters).

**Comment by phstanek** [comment]
Part 1 has been published to APD Development, and is now ready to test.  I have written the following test plan:

[Test Plan for APD-Enhancements Issue 1 Part 1.docx](https://github.com/AquaAerobicSystemsInc/APD-Enhancements/files/2266721/Test.Plan.for.APD-Enhancements.Issue.1.Part.1.docx)

**Comment by phstanek** [comment]
Jakob Nowicki has been assigned as Tester for Part 1.

**Comment by phstanek** [comment]
While reviewing the Digester DDM Mixer Calcs form for Part 2, I noticed that the Est. Walkway Overhang was not updating the database (just defaulting to 1.25 every time).  The fix will be rolled into Part 2 of this issue.

**Comment by phstanek** [comment]
Test Results Summary:  Testing on Part 1 has revealed (1) major issue that will need to be resolved:  The Est. Walkway Overhang is a horizontal distance, and not the Anchor Point that should be used in the equation.  The Anchor Point should be its own field saving separately to the database, and should be editable with a default value of (Freeboard) – (Top/Wall To Mooring Pt).
The SBR->Select Equipment->DDM Mixer Calcs->Mixer Mooring Calcs interface will be updated accordingly and testing will be rolled into the Digester interface testing (Part 2).

**Comment by phstanek** [comment]
Part 2 has been checked in as Changeset 467 and is ready for testing on APD Dev. Do not merge.
Here is the test plan and the spreadsheet it refers to::
[Test Plan for APD-Enhancements Issue 1 Part 2.docx](https://github.com/AquaAerobicSystemsInc/APD-Enhancements/files/2284490/Test.Plan.for.APD-Enhancements.Issue.1.Part.2.docx)
[Test Plan for APD-Enhancements Issue 1 Part 2_Calculations.xlsx](https://github.com/AquaAerobicSystemsInc/APD-Enhancements/files/2284495/Test.Plan.for.APD-Enhancements.Issue.1.Part.2_Calculations.xlsx)

**Comment by phstanek** [comment]
After review of the underlying equations during Part 2 initial testing, it has been decided that the equations will need to be revised - this item will be put on hold until next week when Manuel is back in the office and everything can be finalized.

**Comment by phstanek** [comment]
After sending a full breakdown of the calculations APD is currently performing, Manuel would like to meet with Jakob and myself again to finalize.

**Comment by phstanek** [comment]
Manuel, Jakob, and myself met this morning to finalize.  Summary:
1.  The equation to use for the angle w/dewatering posts will be the same as the existing calculation APD is performing for the Angle @ LWL, substituting (Post Length + 0.25 ft) for LWL.  The 0.25 ft is to account for the distance from the bottom of the float to the LWL.
2. Selectable post lengths will be from 6-13', at 1/2' increments.
3. If a post length is chosen that is greater than (LWL - 1.5 ft), a warning will be displayed.
4. If the angle w/dewatering posts is >= 45 degrees, a warning will be displayed.

**Comment by phstanek** [comment]
The revised update has been published to APD Development and is ready to be tested.

Test Plan (and spreadsheet to assist in testing):
[Test Plan for APD-Enhancements Issue 1 - Mixer Pivotal Mooring with Dewatering Posts.docx](https://github.com/AquaAerobicSystemsInc/APD-Enhancements/files/2443195/Test.Plan.for.APD-Enhancements.Issue.1.-.Mixer.Pivotal.Mooring.with.Dewatering.Posts.docx)
[Test Plan for APD-Enhancements Issue 1 - Mixer Pivotal Mooring with Dewatering Posts_Attachment A.xlsx](https://github.com/AquaAerobicSystemsInc/APD-Enhancements/files/2443205/Test.Plan.for.APD-Enhancements.Issue.1.-.Mixer.Pivotal.Mooring.with.Dewatering.Posts_Attachment.A.xlsx)

**Comment by phstanek** [comment]
Manuel has suggested added a visible note when posts are selected that informs the user that the parts must still be added manually (as they are not part of the autobuild). Once current testing is completed, I will add this feature prior to release.
Eventually, if additional parts are created at the 1/2 increments which are listed in the new dropdown, it will be possible to incorporate them into the autobuild.

**Comment by phstanek** [comment]
The first round of testing has revealed 2 issues affected both SBR and Digester interfaces:
[Test Plan for APD-Enhancements Issue 1 - Mixer Pivotal Mooring with Dewatering Posts_TESTED-1.docx](https://github.com/AquaAerobicSystemsInc/APD-Enhancements/files/2566142/Test.Plan.for.APD-Enhancements.Issue.1.-.Mixer.Pivotal.Mooring.with.Dewatering.Posts_TESTED-1.docx)

1. The new _Angle @ Dewatered w/Posts_ is not updating when the _Top/Wall To Mooring Pt_ is changed.  
After investigation, it was found to only be updating if <ENTER> was hit after changing it.  I have updated the calculation to also fire during the **Validating** event on the _Top/Wall to Mooring Pt_ field, which appears to correct the problem.

2. The existing _Angle @ Low Level_ and _Angle @ Mid-Depth_ fields are not updating when the mixer is changed (while the new _Angle @ Dewatered w/Posts_ is updating correctly).
I have added code to run the main re-calculation routine when the **Mixer Mooring Calcs** button is clicked (if pivotal mooring is selected).

I have also added the recommended note to remind users to manually add dewatering posts if any are selected.

The update has been checked in as Changeset 705 and published to APD Development to be re-tested.

**Comment by phstanek** [comment]
Re-testing has concluded, and the (2) issues above should now be resolved.
[Test Plan for APD-Enhancements Issue 1 - Mixer Pivotal Mooring with Dewatering Posts_RE-TEST.docx](https://github.com/AquaAerobicSystemsInc/APD-Enhancements/files/2572816/Test.Plan.for.APD-Enhancements.Issue.1.-.Mixer.Pivotal.Mooring.with.Dewatering.Posts_RE-TEST.docx)

**Comment by phstanek** [comment]
The update has been released to APD Live 11/14/18 at 7:30am.
