### ISSUE TITLE
Additional panel BOM Filters

### ISSUE THREAD

**Issue by chukon** [AquaAerobicSystemsInc/APD-Enhancements#3]
When more than one filter is in the design we manually need to add 4 hours engineering per panel.

**Comment by phstanek** [comment]
After discussing with Mark, the update is to be applied to AquaDisk and AquaPrime (AquaDiamond appears to be adding shop check-out time in the Engineering section).

This update will automatically add 4 additional hours for each additional filter unit (a process that is now being done manually).

The additional hours will be added to the existing Elec. Programming line on the BOM:
![image](https://user-images.githubusercontent.com/41307105/45550061-6e46ca80-b7ef-11e8-86b1-ae3aa66c59f5.png)

**Comment by phstanek** [comment]
This update has been published to APD Development and is ready to be tested.

Test Plan:
[Test Plan for APDEnhancements_Issue 003 - Additional Eng Hours with Multiple Filter Units.docx](https://github.com/AquaAerobicSystemsInc/APD-Enhancements/files/2415174/Test.Plan.for.APDEnhancements_Issue.003.-.Additional.Eng.Hours.with.Multiple.Filter.Units.docx)

**Comment by phstanek** [comment]
Testing has been completed - no issues found.

Completed Test Plan:
[Test Plan for APDEnhancements_Issue 003 - Additional Eng Hours with Multiple Filter Units_COMPLETED.docx](https://github.com/AquaAerobicSystemsInc/APD-Enhancements/files/2421368/Test.Plan.for.APDEnhancements_Issue.003.-.Additional.Eng.Hours.with.Multiple.Filter.Units_COMPLETED.docx)

**Comment by phstanek** [comment]
This update (Changeset 583) has been released to APD Live, and this issue can now be closed.
