### ISSUE TITLE
AquaSBR 4-basin Shares aeration air valves account

### ISSUE THREAD

**Issue by chukon** [AquaAerobicSystemsInc/APD-Enhancements#5]
Making the default 7 instead of 4 will save time.

**Comment by phstanek** [comment]
Chuck,

I believe this is a duplicate issue to the **APD-Top-APD-Quick-Wins** Issue 5:
**With a four basin SBR system, the recommended quantity of air control valves is 4, but should be 7.**

I'm already working on the solution to that issue.

Thanks,

Paul

**Comment by phstanek** [comment]
This issue has been resolved by APD-Top-APD-Quick-Wins Issue 5 and can now be closed.
